version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

    environment:
      - CHOKIDAR_USEPOLLING=true